# Generated by Django 3.0.2 on 2020-03-01 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.PositiveIntegerField(null=True)),
                ('dexterity', models.PositiveIntegerField(null=True)),
                ('constitution', models.PositiveIntegerField(null=True)),
                ('intelligence', models.PositiveIntegerField(null=True)),
                ('wisdom', models.PositiveIntegerField(null=True)),
                ('charisma', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=255)),
                ('action_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morality', models.PositiveIntegerField(choices=[(0, 'Good'), (1, 'Neutral'), (2, 'Evil')])),
                ('lawfulness', models.PositiveIntegerField(choices=[(0, 'Lawful'), (1, 'Neutral'), (1, 'Chaotic')])),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sense', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(choices=[('AC', 'Acrobatics'), ('AH', 'Animal Handling'), ('AC', 'Arcana'), ('AT', 'Athletics'), ('DE', 'Deception'), ('HI', 'History'), ('INS', 'Insight'), ('INT', 'Intimidation'), ('INV', 'Investigation'), ('ME', 'Medicine'), ('NA', 'Nature'), ('PERC', 'Perception'), ('PERS', 'Persuasion'), ('RE', 'Religion'), ('SOH', 'Sleight of Hand'), ('ST', 'Stealth'), ('SU', 'Survival')])),
                ('modifier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('W', 'walking'), ('F', 'flying'), ('S', 'swimming'), ('C', 'climbing')])),
                ('rate', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_name', models.CharField(max_length=255)),
                ('trait_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LegendaryAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Action')),
                ('action_cost', models.PositiveIntegerField()),
            ],
            bases=('api.action',),
        ),
        migrations.CreateModel(
            name='Combatant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('size', models.TextField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan')])),
                ('ac', models.PositiveIntegerField(null=True)),
                ('max_hp', models.PositiveIntegerField(null=True)),
                ('ability_scores', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.AbilityScores')),
                ('actions', models.ManyToManyField(related_name='action', to='api.Action')),
                ('alignment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Alignment')),
                ('lair_actions', models.ManyToManyField(related_name='lair_action', to='api.Action')),
                ('languages', models.ManyToManyField(to='api.Language')),
                ('reactions', models.ManyToManyField(related_name='reaction', to='api.Action')),
                ('senses', models.ManyToManyField(to='api.Sense')),
                ('skills', models.ManyToManyField(to='api.Skill')),
                ('speeds', models.ManyToManyField(to='api.Speeds')),
                ('traits', models.ManyToManyField(to='api.Trait')),
                ('legendary_actions', models.ManyToManyField(to='api.LegendaryAction')),
            ],
        ),
    ]
