# Generated by Django 3.0.2 on 2020-03-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sense',
            name='range',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='lawfulness',
            field=models.PositiveIntegerField(choices=[(0, 'Lawful'), (1, 'Neutral'), (2, 'Chaotic')]),
        ),
    ]
